name: SIO221A-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - xarray
  - nc-time-axis
  - holoviews
  - bokeh
  - hvplot
  - datashader
  - pip
  - pip:
    - netcdf4==1.4.2
  
