name: SIO221A-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - libnetcdf==4.6.1
  - numpy==1.16.4
  - matplotlib==3.1.0
  - netcdf4==1.4.2
  - xarray==0.12.1
  - nc-time-axis==1.2.0
  - holoviews==1.12.3
  - bokeh==1.2.0
  - hvplot==0.4.0
  - datashader==0.7.0
  
