name: SIO221A-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - libnetcdf=4.7.0
  - numpy==1.16.4
    #  - matplotlib==3.1.0
  #- netcdf4==1.4.2
  - xarray
    #- nc-time-axis
    #- holoviews
    #- bokeh
    #- hvplot
    #- datashader
  
